// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Project;
import com.test.interceptor.domain.Story;
import java.util.Set;

privileged aspect Project_Roo_JavaBean {
    
    public String Project.getName() {
        return this.name;
    }
    
    public void Project.setName(String name) {
        this.name = name;
    }
    
    public Set<Story> Project.getStories() {
        return this.stories;
    }
    
    public void Project.setStories(Set<Story> stories) {
        this.stories = stories;
    }
    
}
