// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Story;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Story_Roo_Configurable {
    
    declare @type: Story: @Configurable;
    
}
