// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Story;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Story_Roo_Json {
    
    public String Story.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Story Story.fromJsonToStory(String json) {
        return new JSONDeserializer<Story>().use(null, Story.class).deserialize(json);
    }
    
    public static String Story.toJsonArray(Collection<Story> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Story> Story.fromJsonArrayToStorys(String json) {
        return new JSONDeserializer<List<Story>>().use(null, ArrayList.class).use("values", Story.class).deserialize(json);
    }
    
}
