// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Project;
import com.test.interceptor.domain.Story;

privileged aspect Story_Roo_JavaBean {
    
    public String Story.getName() {
        return this.name;
    }
    
    public void Story.setName(String name) {
        this.name = name;
    }
    
    public Project Story.getProject() {
        return this.project;
    }
    
    public void Story.setProject(Project project) {
        this.project = project;
    }
    
}
