// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Project;
import com.test.interceptor.domain.Story;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Story_Roo_Finder {
    
    public static TypedQuery<Story> Story.findStorysByProject(Project project) {
        if (project == null) throw new IllegalArgumentException("The project argument is required");
        EntityManager em = Story.entityManager();
        TypedQuery<Story> q = em.createQuery("SELECT o FROM Story AS o WHERE o.project = :project", Story.class);
        q.setParameter("project", project);
        return q;
    }
    
}
