// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.Story;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Story_Roo_Jpa_Entity {
    
    declare @type: Story: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Story.id;
    
    @Version
    @Column(name = "version")
    private Integer Story.version;
    
    public Long Story.getId() {
        return this.id;
    }
    
    public void Story.setId(Long id) {
        this.id = id;
    }
    
    public Integer Story.getVersion() {
        return this.version;
    }
    
    public void Story.setVersion(Integer version) {
        this.version = version;
    }
    
}
