// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.interceptor.domain;

import com.test.interceptor.domain.ProjectDataOnDemand;
import com.test.interceptor.domain.Story;
import com.test.interceptor.domain.StoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StoryDataOnDemand: @Component;
    
    private Random StoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Story> StoryDataOnDemand.data;
    
    @Autowired
    ProjectDataOnDemand StoryDataOnDemand.projectDataOnDemand;
    
    public Story StoryDataOnDemand.getNewTransientStory(int index) {
        Story obj = new Story();
        setName(obj, index);
        return obj;
    }
    
    public void StoryDataOnDemand.setName(Story obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
    public Story StoryDataOnDemand.getSpecificStory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Story obj = data.get(index);
        Long id = obj.getId();
        return Story.findStory(id);
    }
    
    public Story StoryDataOnDemand.getRandomStory() {
        init();
        Story obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Story.findStory(id);
    }
    
    public boolean StoryDataOnDemand.modifyStory(Story obj) {
        return false;
    }
    
    public void StoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Story.findStoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Story' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Story>();
        for (int i = 0; i < 10; i++) {
            Story obj = getNewTransientStory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
